### ISSUE TITLE
Suggestion to add headlight and horn wiremod inputs

### ISSUE THREAD

**Issue by Paul0Paulerlings** [StyledStrike/gmod-glide#16]
As the issue name suggests, maybe adding a wiremod input/output for toggling the headlights and activating the horn of the vehicle might be interesting. However, the horn might get spammed, but its no different from an auto-clicker in that sort of edge-case. Not sure if this is the right place to put a suggestion, but that's because I don't use github often.

**Comment by StyledStrike** [comment]
This should be fine, though I will have to disable the click sounds when switching headlights wire Wiremod, since that could be spammed.

**Comment by StyledStrike** [comment]
Added in 89e12613f0189863e6e14957854107598eef9306
